### ISSUE TITLE
Problem with check finiteness define

### ISSUE THREAD

**Issue by azrafe7** [nanjizal/hxSpiro#1]
Around here: https://github.com/nanjizal/hxSpiro/blob/55590ef7bf015d16eaa4ab81f80f0285f6b3d6f7/hxSpiro/Spiro.hx#L316
the define is not handled correctly.

I've tried adding support for the define and it _seems_ to work when it follows the path of `CHECK_INPUT_FINITENESS=false`:

```haxe
    public static /* inline */ function setupPath( src:Vector<ControlPoint>, n: Int ): Vector<Segment> {
        // Verify that input values are within realistic limits
        var r: Vector<Segment> = null;
        var rValid: Bool = true;
        
#if (CHECK_INPUT_FINITENESS)
        for( i in 0...n ){
            if( !Math.isFinite( src[ i ].x ) || !Math.isFinite( src[ i ].y ) ) {
                r = null;
                rValid = false;
                break;
            }
        }
#end
        trace( 'setupPath rValid =' + rValid );
        if( rValid ) {
            var n_seg = src[0].pointType == OpenContour ? n - 1 : n;
            r = new Vector<Segment>( n_seg + 1 );
            for( j in 0...( n_seg + 1 )) {
                r[ j ] = new Segment();
            }
            for (i in 0...n_seg ){
                var seg = r[i];
                var srci = src[i];
                seg.x = srci.x;
                seg.y = srci.y;
                seg.pointType = srci.pointType;
                seg.ks[ 0 ] = 0.0;
                seg.ks[ 1 ] = 0.0;
                seg.ks[ 2 ] = 0.0;
                seg.ks[ 3 ] = 0.0;
            }
            trace( '... r ' + r );
            r[ n_seg ].x = src[ n_seg % n ].x;
            r[ n_seg ].y = src[ n_seg % n ].y;
            r[ n_seg ].pointType = src[ n_seg % n ].pointType;
            var dx: Float;
            var dy: Float;
            for (i in 0...n_seg ){
                dx = r[ i + 1 ].x - r[ i ].x;
                dy = r[ i + 1 ].y - r[ i ].y;
                
#if (!CHECK_INPUT_FINITENESS)
                r[ i ].dChord = hyp( dx, dy );
#else
                if( Math.isFinite( dx ) || Math.isFinite( dy ) || Math.isFinite( ( r[ i ].dChord = hyp( dx, dy ) )) ) 
                {
                    rValid = false;
                    break;
                }
#end
                
                r[ i ].segment_theta = Math.atan2( dy, dx );
            }
            if( rValid ){
                var ilast = n_seg - 1;
                var pType: PointType;
                for( i in 0...n_seg ){
                    pType = r[ i ].pointType;
                    if( pType == OpenContour || pType == EndOpenContour || pType == Corner ){
                        r[ i ].bend_theta = 0.0;
                    } else {
                        r[ i ].bend_theta = mod2pi( r[ i ].segment_theta - r[ ilast ].segment_theta );
                    }
                    ilast = i;
                }
            }
        }
        
        return r;
    }
```

Out of curiosity, can I ask how are you planning to use this lib?

**Comment by azrafe7** [comment]
And this https://github.com/nanjizal/hxSpiro/blob/55590ef7bf015d16eaa4ab81f80f0285f6b3d6f7/hxSpiro/Spiro.hx#L317
should be inverted to

```haxe
if( !Math.isFinite( dx ) || !Math.isFinite( dy ) || !Math.isFinite( ( r[ i ].dChord = hyp( dx, dy ) )) ) 
```

With this change it seems to work also with `-D CHECK_INPUT_FINITENESS`.

**Comment by nanjizal** [comment]
oops did not see this, guess I am not checking my email so much. The second one I spotted today when debugging the code and made some other changes it's now working. Is your first suggestion still relevant - now stuff is working better the demo is rather rough but seems to work ( 30 clicks to draw a curve you can change that easily ).
In terms of use it's got rather a limited licence thought it would be nice to perhaps use in Kha with triangles for creating vectors and fonts that could then be used in apps.  I contacted the guy who wrote the phd/originals he has a patent and wanted it to stay same licence I don't know if I really have to outside US in theory, disappointed he was not up for going with MIT.

**Comment by azrafe7** [comment]
Yes, I would retain the define in there so the user can freely choose to run the checks or not. As it is now it always runs the _slightly-more_ expensive code path.

**Comment by nanjizal** [comment]
Ah I see now, I read your post when I was tired it makes more sense now.

**Comment by nanjizal** [comment]
I actually improved slightly by removing the if( rValid ) if there is no **-D checkFitness** and there was another fitness part I also included hopefully ok still seems to work both ways.
